/**
 * Inline the Lucide icons we use into a TypeScript module.
 *
 * Icons are compiled in rather than fetched: the zero-network rule forbids a
 * CDN, and shipping ~20 individual SVG requests for a control panel is worse
 * than a few KB of inlined markup. Only the listed icons are included, so the
 * cost stays proportional to what is actually used.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const iconsDir = join(here, '..', 'node_modules', 'lucide-static', 'icons');
const out = join(here, '..', 'src', 'icons.ts');

const ICONS = [
  'audio-lines',
  'bell',
  'brain',
  'check',
  'chevron-right',
  'circle-alert',
  'clock',
  'cpu',
  'ellipsis',
  'loader',
  'mic',
  'notebook-pen',
  'pencil',
  'power',
  'refresh-cw',
  'settings',
  'sliders-horizontal',
  'trash-2',
  'wrench',
  'x',
  'zap',
];

const entries = ICONS.map((name) => {
  const svg = readFileSync(join(iconsDir, `${name}.svg`), 'utf8')
    // The licence comment is identical in every file; it is carried once at
    // the top of the generated module instead of twenty-one times.
    .replace(/<!--[\s\S]*?-->/g, '')
    // Strip the fixed size so CSS controls it, and let the stroke inherit
    // colour from whatever the icon sits in.
    .replace(/\s(width|height)="[^"]*"/g, '')
    .replace(/stroke="[^"]*"/, 'stroke="currentColor"')
    .replace(/\s+/g, ' ')
    .trim();
  return `  '${name}': ${JSON.stringify(svg)},`;
}).join('\n');

writeFileSync(
  out,
  `// GENERATED by scripts/build-icons.mjs — do not edit.\n` +
    `// Lucide icons, inlined at build time. Add a name to ICONS there.\n` +
    `// Lucide is ISC licensed: https://lucide.dev — see node_modules/lucide-static.\n\n` +
    `export const icons = {\n${entries}\n} as const;\n\n` +
    `export type IconName = keyof typeof icons;\n`,
);

console.log(`wrote ${ICONS.length} icons to src/icons.ts`);
