/**
 * Vendor highlight.js into public/vendor/hljs, for code blocks in her replies.
 *
 * The ES module build from @highlightjs/cdn-assets: the core, and only the
 * languages a reply is likely to hold, registered by a small generated
 * index.mjs that an import map in index.html points "hljs" at. The whole
 * library with every grammar is 316 KB; this is a fraction of that.
 */

import { copyFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const from = join(here, '..', 'node_modules', '@highlightjs', 'cdn-assets', 'es');
const to = join(here, '..', 'public', 'vendor', 'hljs');

/** Grammars to ship. Aliases (py, js, ts, sh, ps1, html…) come with them. */
const LANGUAGES = [
  'bash',
  'c',
  'cpp',
  'csharp',
  'css',
  'diff',
  'dos',
  'go',
  'ini',
  'java',
  'javascript',
  'json',
  'lua',
  'markdown',
  'plaintext',
  'powershell',
  'python',
  'rust',
  'shell',
  'sql',
  'typescript',
  'xml',
  'yaml',
];

mkdirSync(join(to, 'languages'), { recursive: true });
copyFileSync(join(from, 'core.min.js'), join(to, 'core.min.js'));

const lines = ["import hljs from './core.min.js';"];
for (const name of LANGUAGES) {
  copyFileSync(
    join(from, 'languages', `${name}.min.js`),
    join(to, 'languages', `${name}.min.js`),
  );
  const id = `lang_${name}`;
  lines.push(`import ${id} from './languages/${name}.min.js';`);
  lines.push(`hljs.registerLanguage('${name}', ${id});`);
}
lines.push('export default hljs;');

writeFileSync(
  join(to, 'index.mjs'),
  `/* GENERATED by scripts/vendor-hljs.mjs — do not edit.\n` +
    ` * highlight.js 11, BSD-3-Clause: https://highlightjs.org */\n` +
    `${lines.join('\n')}\n`,
);

console.log(
  `vendored highlight.js with ${LANGUAGES.length} languages to public/vendor/hljs`,
);
