/**
 * Vendor the Lucide modules this panel uses into public/vendor/lucide.
 *
 * Lucide's own API is used — createElement() over icon data — rather than
 * scraping SVG text. The only thing that needs solving is that browsers
 * cannot resolve the bare specifier "lucide" without a bundler, and importing
 * its barrel would pull all 1852 icon modules. So the icons actually used are
 * copied out with a small barrel of their own, and an import map in index.html
 * points "lucide" at it. Source stays `import { Bell } from 'lucide'`.
 */

import { copyFileSync, existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const from = join(here, '..', 'node_modules', 'lucide', 'dist', 'esm');
const to = join(here, '..', 'public', 'vendor', 'lucide');

/** Exported names, as Lucide spells them. File names are derived. */
const ICONS = [
  'AudioLines',
  'ArrowLeft',
  'Bell',
  'Brain',
  'Check',
  'ChevronRight',
  'CircleAlert',
  'Clock',
  'CirclePlus',
  'Cpu',
  'FileText',
  'Ellipsis',
  'Keyboard',
  'LoaderCircle',
  'Mic',
  'NotebookPen',
  'Pencil',
  'Plus',
  'Power',
  'RefreshCw',
  'RotateCcw',
  'Save',
  'Settings',
  'SlidersHorizontal',
  'Trash',
  'TriangleAlert',
  'Wrench',
  'X',
  'Zap',
];

const kebab = (name) =>
  name
    .replace(/([a-z\d])([A-Z])/g, '$1-$2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1-$2')
    // Digits are their own segment: Trash2 is trash-2.mjs, not trash2.mjs.
    .replace(/([a-zA-Z])(\d)/g, '$1-$2')
    .toLowerCase();

mkdirSync(join(to, 'icons'), { recursive: true });

for (const file of ['createElement.mjs', 'defaultAttributes.mjs']) {
  copyFileSync(join(from, file), join(to, file));
}

const lines = ["export { default as createElement } from './createElement.mjs';"];
for (const name of ICONS) {
  const file = `${kebab(name)}.mjs`;
  const source = join(from, 'icons', file);
  if (!existsSync(source)) {
    // Fail loudly with the name to fix, rather than shipping a barrel that
    // half works and breaks at import time in the browser.
    throw new Error(`no lucide icon file for ${name} (looked for ${file})`);
  }
  copyFileSync(source, join(to, 'icons', file));
  lines.push(`export { default as ${name} } from './icons/${file}';`);
}

writeFileSync(
  join(to, 'index.mjs'),
  `/* GENERATED by scripts/vendor-lucide.mjs — do not edit.\n` +
    ` * Lucide v1.47.0, ISC licensed: https://lucide.dev\n` +
    ` * Only the icons this panel uses; add one to ICONS in that script.\n */\n` +
    `${lines.join('\n')}\n`,
);

console.log(`vendored ${ICONS.length} lucide icons to public/vendor/lucide`);
