r"""Write THIRD-PARTY-NOTICES.md from what is actually installed.

    uv run python packaging\notices.py

Naka ships other people's work: a frozen tray full of Python packages, a
llama.cpp build, icons in the panel, and weights that come with terms of
their own. This reads the metadata of every package in an environment —
rather than a list kept by hand, which goes stale the first time a
dependency changes — and adds the pieces that have no dist-info.

It reads both environments when they exist: the build venv, whose packages
are inside Naka.exe, and the runtime venv that setup installs. The result is
committed, and the installer ships it beside the executable.
"""

import sys
from email.parser import Parser
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "THIRD-PARTY-NOTICES.md"


def _runtime_venv() -> Path:
    """The runtime setup installs, if this machine has one; a checkout's
    .venv holds the same packages and is the fallback."""
    sys.path.insert(0, str(ROOT))
    from server import paths

    installed = paths.RUNTIME / "venv"
    return installed if (installed / "Lib").exists() else ROOT / ".venv"


ENVIRONMENTS = (
    ("In Naka.exe", ROOT / "build" / "venv"),
    ("Installed by setup, into the data folder", _runtime_venv()),
)

# In the build venv but not in the executable: PyInstaller and what it needs
# to do its work. They build Naka.exe; they are not part of it.
BUILD_ONLY = {"altgraph", "macholib", "pefile", "pyinstaller",
              "pyinstaller-hooks-contrib", "pywin32-ctypes", "setuptools"}

# Everything that ships without Python metadata to read. Versions that move
# — llama.cpp's build, the models — are named in packaging/manifest/*.json,
# which is where setup takes them from.
OTHERS = """\
### Not Python packages

| Component | Licence | Where it comes from |
|---|---|---|
| llama.cpp (`llama-server.exe` and its CUDA build) | MIT | https://github.com/ggml-org/llama.cpp |
| CUDA runtime libraries shipped with that build | NVIDIA CUDA EULA | https://docs.nvidia.com/cuda/eula/ |
| uv | Apache-2.0 or MIT | https://github.com/astral-sh/uv |
| CPython, as uv installs it | PSF-2.0 | https://www.python.org/ |
| Lucide icons (vendored into the panel) | ISC | https://lucide.dev/ |
| highlight.js (vendored into the panel) | BSD-3-Clause | https://highlightjs.org/ |
| Simple Icons brand logos (vendored into the panel; the logos are their owners' trademarks) | CC0-1.0 | https://simpleicons.org/ |
| Microsoft Edge WebView2 runtime | Microsoft terms | https://developer.microsoft.com/microsoft-edge/webview2/ |
| Inno Setup (builds the installer; not shipped) | Inno Setup Licence | https://jrsoftware.org/ |

### Models, downloaded on first run

Weights are not part of this program. They are fetched from their publishers
and are used under their own terms, which are worth reading before shipping
anything built on them.

| Model | Licence | Where it comes from |
|---|---|---|
| Gemma 4 12B (QAT, Q4_0 GGUF) | Gemma Terms of Use | https://ai.google.dev/gemma/terms |
| Qwen3 14B (GGUF) | Apache-2.0 | https://huggingface.co/Qwen/Qwen3-14B |
| faster-whisper large-v3-turbo | MIT | https://huggingface.co/mobiuslabsgmbh/faster-whisper-large-v3-turbo |
| Kokoro-82M, with its voices | Apache-2.0 | https://huggingface.co/hexgrad/Kokoro-82M |
| spaCy `en_core_web_sm` | MIT | https://github.com/explosion/spacy-models |
"""


def licence_of(dist: Path) -> str:
    """The licence a package declares, from its metadata."""
    metadata = dist / "METADATA"
    if not metadata.exists():
        return "see the package"
    headers = Parser().parsestr(metadata.read_text(encoding="utf-8", errors="replace"),
                                headersonly=True)
    expression = headers.get("License-Expression")
    if expression:
        return expression
    classifiers = [c.split("::")[-1].strip() for c in headers.get_all("Classifier", [])
                   if c.startswith("License ::")]
    if classifiers:
        return ", ".join(dict.fromkeys(classifiers))
    declared = (headers.get("License") or "").strip()
    if declared and "\n" not in declared and len(declared) < 60:
        return declared
    return "see the package"


def packages(venv: Path, skip: set[str] = frozenset()) -> list[tuple[str, str, str]]:
    site = venv / "Lib" / "site-packages"
    found = {}
    for dist in sorted(site.glob("*.dist-info")):
        name, _, version = dist.name.removesuffix(".dist-info").rpartition("-")
        if name.lower().replace("_", "-") in skip:
            continue
        found[name.lower()] = (name, version, licence_of(dist))
    return [found[key] for key in sorted(found)]


def main() -> int:
    lines = [
        "# Third-party notices",
        "",
        "Naka is built on the work below, each under its own licence. This file",
        "is generated by `packaging/notices.py` from the packages actually",
        "installed, so it says what a build really contains rather than what a",
        "list once said.",
        "",
    ]
    for title, venv in ENVIRONMENTS:
        skip = BUILD_ONLY if "build" in venv.parts else frozenset()
        entries = packages(venv, skip) if (venv / "Lib" / "site-packages").exists() else []
        if not entries:
            print(f"! {venv} is not installed; its packages are missing from the notices",
                  file=sys.stderr)
            continue
        lines += [f"### {title}", "", "| Package | Version | Licence |", "|---|---|---|"]
        lines += [f"| {name} | {version} | {licence} |" for name, version, licence in entries]
        lines += [""]
    lines += [OTHERS]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
